# ursprüngliche Nodeport-Version zum testen
# ist noch im Projekt, ist aber auch in kustomization.yaml auskommentiert
apiVersion: v1
kind: Service
metadata:
  name: redmine-nodeport
spec:
  selector:
    app: redmine
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
