apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redmine-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redmine
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres
  namespaceSelector:
    any: true
  endpoints:
    - port: postgres
      interval: 30s
